# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
builds:
  - main: ./cmd/pipe/main.go
    env:
    - CGO_ENABLED=0
    ldflags:
    - -s -w -X "main.Rev={{.Tag}}-{{.ShortCommit}}"
archive:
  replacements:
    darwin: osx
    linux: linux
    windows: windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
  github:
    owner: relvacode
    name: homebrew-pipe
