language: go
sudo: false

addons:
  apt:
    packages:
    - curl
    # needed for the nfpm pipe:
#    - rpm

matrix:
  include:
  - go: 1.x
    env: LATEST=true
  - go: 1.10.x
  - go: 1.11.x
  - go: tip
  allow_failures:
  - go: tip

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: os = linux AND env(LATEST) = true
